
    create table add_drop_periods (
        add_end date,
        add_start date,
        drop_end date,
        id bigint generated by default as identity,
        semester_id bigint not null,
        primary key (id)
    );

    create table assessment_components (
        locked boolean not null,
        published boolean not null,
        weight_percent float(53) not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        subject_offering_id bigint not null,
        name varchar(255) not null,
        status varchar(255) check ((status in ('DRAFT','PUBLISHED','LOCKED'))),
        type varchar(255) not null check ((type in ('QUIZ','MIDTERM','FINAL','LAB','PROJECT','OTHER'))),
        primary key (id)
    );

    create table attendance_sessions (
        class_date date not null,
        locked boolean not null,
        created_at timestamp(6) with time zone not null,
        created_by_teacher_id bigint,
        id bigint generated by default as identity,
        subject_offering_id bigint not null,
        primary key (id),
        unique (subject_offering_id, class_date)
    );

    create table attendances (
        date date,
        attendance_session_id bigint,
        id bigint generated by default as identity,
        student_id bigint not null,
        subject_offering_id bigint not null,
        reason varchar(255),
        status varchar(255) check ((status in ('PRESENT','LATE','ABSENT'))),
        primary key (id),
        unique (student_id, subject_offering_id, date)
    );

    create table audit_logs (
        actor_user_id bigint,
        created_at timestamp(6) with time zone not null,
        entity_id bigint,
        id bigint generated by default as identity,
        action varchar(255) not null,
        actor_email varchar(255),
        details TEXT,
        entity_type varchar(255) not null,
        primary key (id)
    );

    create table charges (
        amount numeric(38,2),
        due_date date,
        id bigint generated by default as identity,
        student_id bigint not null,
        description varchar(255),
        status varchar(255) check ((status in ('PENDING','PAID','PARTIAL','OVERDUE'))),
        primary key (id)
    );

    create table checklist_items (
        completed boolean not null,
        deadline date,
        id bigint generated by default as identity,
        student_id bigint not null,
        link_to_section varchar(255),
        title varchar(255),
        primary key (id)
    );

    create table checklist_templates (
        active boolean not null,
        offset_days integer not null,
        id bigint generated by default as identity,
        link_to_section varchar(255),
        title varchar(255) not null,
        trigger_event varchar(255) not null check ((trigger_event in ('ENROLLMENT','SEMESTER_START','SEMESTER_END','CLEARANCE_START'))),
        primary key (id)
    );

    create table clearance_checkpoints (
        clearance_sheet_id bigint not null,
        id bigint generated by default as identity,
        comment varchar(255),
        department varchar(255),
        status varchar(255) check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (id)
    );

    create table clearance_sheets (
        id bigint generated by default as identity,
        student_id bigint not null,
        status varchar(255) check ((status in ('IN_PROGRESS','CLEARED'))),
        primary key (id)
    );

    create table course_announcements (
        pinned boolean not null,
        public_visible boolean not null,
        published boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        published_at timestamp(6) with time zone,
        scheduled_at timestamp(6) with time zone,
        subject_offering_id bigint,
        teacher_id bigint not null,
        updated_at timestamp(6) with time zone,
        content TEXT not null,
        title varchar(255) not null,
        primary key (id)
    );

    create table course_materials (
        published boolean not null,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        size_bytes bigint not null,
        subject_offering_id bigint not null,
        updated_at timestamp(6) with time zone,
        uploaded_by_teacher_id bigint not null,
        content_type varchar(255),
        description TEXT,
        original_file_name varchar(255) not null,
        storage_path varchar(255) not null,
        title varchar(255) not null,
        visibility varchar(255) not null check ((visibility in ('ENROLLED_ONLY','PUBLIC'))),
        primary key (id)
    );

    create table exam_schedules (
        exam_date date,
        exam_time time(0),
        id bigint generated by default as identity,
        subject_offering_id bigint not null,
        format varchar(255),
        room varchar(255),
        primary key (id)
    );

    create table faculties (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table file_assets (
        id bigint generated by default as identity,
        linked_entity_id bigint,
        owner_student_id bigint,
        size_bytes bigint not null,
        uploaded_at timestamp(6) with time zone not null,
        uploaded_by_user_id bigint,
        category varchar(255) not null check ((category in ('STUDENT_FILE','REQUEST_ATTACHMENT','MOBILITY_DOCUMENT','PAYMENT_RECEIPT','TRANSCRIPT_PDF','OTHER'))),
        content_type varchar(255),
        linked_entity_type varchar(255),
        original_name varchar(255) not null,
        storage_path varchar(255) not null,
        primary key (id)
    );

    create table final_grades (
        numeric_value float(53) not null,
        points float(53) not null,
        published boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        published_at timestamp(6) with time zone,
        student_id bigint not null,
        subject_offering_id bigint not null,
        updated_at timestamp(6) with time zone,
        letter_value varchar(255),
        status varchar(255) check ((status in ('CALCULATED','PUBLISHED','LOCKED'))),
        primary key (id),
        unique (student_id, subject_offering_id)
    );

    create table fx_registrations (
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        student_id bigint not null,
        subject_offering_id bigint not null,
        status varchar(255) check ((status in ('PENDING','APPROVED','PAID','CONFIRMED'))),
        primary key (id)
    );

    create table grade_change_requests (
        new_value float(53) not null,
        old_value float(53),
        applied_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        final_grade_id bigint,
        grade_id bigint,
        id bigint generated by default as identity,
        reviewed_at timestamp(6) with time zone,
        reviewed_by_user_id bigint,
        student_id bigint not null,
        subject_offering_id bigint not null,
        teacher_id bigint not null,
        reason TEXT not null,
        reviewer_comment TEXT,
        status varchar(255) not null check ((status in ('SUBMITTED','APPROVED','REJECTED','APPLIED'))),
        primary key (id)
    );

    create table grades (
        grade_value float(53) not null,
        max_grade_value float(53) not null,
        published boolean not null,
        assessment_component_id bigint,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        student_id bigint not null,
        subject_offering_id bigint not null,
        comment varchar(500),
        grade_type varchar(255) check ((grade_type in ('QUIZ','MIDTERM','FINAL','LAB'))),
        primary key (id)
    );

    create table holds (
        active boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        resolved_at timestamp(6) with time zone,
        student_id bigint not null,
        reason varchar(500),
        type varchar(255) not null check ((type in ('FINANCIAL','ACADEMIC','DISCIPLINARY','MANUAL'))),
        primary key (id)
    );

    create table meeting_times (
        day_of_week smallint not null check ((day_of_week between 0 and 6)),
        end_time time(0) not null,
        start_time time(0) not null,
        id bigint generated by default as identity,
        subject_offering_id bigint not null,
        lesson_type varchar(255) check ((lesson_type in ('LECTURE','PRACTICE','LAB'))),
        room varchar(255),
        primary key (id)
    );

    create table mobility_applications (
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        student_id bigint not null,
        disciplines_mapping TEXT,
        status varchar(255) check ((status in ('DRAFT','SUBMITTED','IN_REVIEW','APPROVED','REJECTED'))),
        university_name varchar(255),
        primary key (id)
    );

    create table news (
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        category varchar(255),
        content TEXT,
        title varchar(255),
        primary key (id)
    );

    create table notifications (
        read boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        link varchar(255),
        message TEXT not null,
        recipient_email varchar(255) not null,
        title varchar(255) not null,
        type varchar(255) not null check ((type in ('ENROLLMENT','SCHEDULE','ATTENDANCE','GRADE','FINAL_GRADE','FINANCE','REQUEST','MOBILITY','CLEARANCE','SYSTEM'))),
        primary key (id)
    );

    create table payments (
        amount numeric(38,2),
        date date,
        charge_id bigint,
        id bigint generated by default as identity,
        student_id bigint not null,
        primary key (id)
    );

    create table programs (
        credit_limit integer not null,
        faculty_id bigint,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table registration_windows (
        active boolean not null,
        end_date date not null,
        start_date date not null,
        id bigint generated by default as identity,
        semester_id bigint not null,
        type varchar(255) not null check ((type in ('REGISTRATION','ADD_DROP','FX','GRADE_PUBLISH'))),
        primary key (id)
    );

    create table registrations (
        created_at timestamp(6) with time zone,
        dropped_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        student_id bigint not null,
        subject_offering_id bigint not null,
        drop_reason varchar(500),
        status varchar(255) check ((status in ('DRAFT','SUBMITTED','CONFIRMED','DROPPED'))),
        primary key (id),
        unique (student_id, subject_offering_id)
    );

    create table request_messages (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        request_id bigint not null,
        sender_user_id bigint not null,
        message TEXT not null,
        primary key (id)
    );

    create table semesters (
        current boolean not null,
        end_date date,
        start_date date,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table social_activities (
        confirmed boolean not null,
        date date,
        hours integer not null,
        id bigint generated by default as identity,
        student_id bigint not null,
        category varchar(255),
        title varchar(255),
        primary key (id)
    );

    create table student_files (
        id bigint generated by default as identity,
        student_id bigint not null,
        uploaded_at timestamp(6) with time zone,
        category varchar(255),
        file_path varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table student_requests (
        assigned_to_user_id bigint,
        closed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        student_id bigint not null,
        updated_at timestamp(6) with time zone,
        category varchar(255),
        description TEXT,
        status varchar(255) check ((status in ('NEW','IN_REVIEW','NEED_INFO','APPROVED','REJECTED','DONE'))),
        primary key (id)
    );

    create table students (
        course integer not null,
        credits_earned integer not null,
        current_semester_id bigint,
        faculty_id bigint,
        id bigint generated by default as identity,
        program_id bigint,
        address varchar(255),
        email varchar(255) not null,
        emergency_contact varchar(255),
        group_name varchar(255),
        name varchar(255),
        passport_number varchar(255),
        phone varchar(255),
        status varchar(255) check ((status in ('ACTIVE','ON_LEAVE','GRADUATED'))),
        primary key (id),
        unique (email)
    );

    create table subject_offerings (
        capacity integer not null,
        day_of_week smallint check ((day_of_week between 0 and 6)),
        end_time time(0),
        start_time time(0),
        id bigint generated by default as identity,
        semester_id bigint not null,
        subject_id bigint not null,
        teacher_id bigint,
        lesson_type varchar(255) check ((lesson_type in ('LECTURE','PRACTICE','LAB'))),
        room varchar(255),
        primary key (id)
    );

    create table subject_prerequisites (
        id bigint generated by default as identity,
        prerequisite_id bigint not null,
        subject_id bigint not null,
        primary key (id),
        unique (subject_id, prerequisite_id)
    );

    create table subjects (
        credits integer not null,
        id bigint generated by default as identity,
        program_id bigint,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table survey_questions (
        id bigint generated by default as identity,
        survey_id bigint not null,
        text TEXT,
        type varchar(255) check ((type in ('SCALE','TEXT'))),
        primary key (id)
    );

    create table survey_responses (
        id bigint generated by default as identity,
        student_id bigint not null,
        submitted_at timestamp(6) with time zone,
        survey_id bigint not null,
        answers_json TEXT,
        primary key (id),
        unique (survey_id, student_id)
    );

    create table surveys (
        anonymous boolean not null,
        end_date date,
        start_date date,
        id bigint generated by default as identity,
        semester_id bigint,
        title varchar(255),
        primary key (id)
    );

    create table teacher_student_notes (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        student_id bigint not null,
        subject_offering_id bigint not null,
        teacher_id bigint not null,
        updated_at timestamp(6) with time zone,
        note TEXT not null,
        risk_flag varchar(255) not null check ((risk_flag in ('NONE','LOW_ATTENDANCE','LOW_GRADES','COMBINED_RISK'))),
        primary key (id)
    );

    create table teachers (
        faculty_id bigint,
        id bigint generated by default as identity,
        bio TEXT,
        department varchar(255),
        email varchar(255) not null,
        name varchar(255),
        office_hours TEXT,
        office_room varchar(255),
        photo_url varchar(255),
        position_title varchar(255),
        public_email varchar(255),
        role varchar(255) check ((role in ('TEACHER','TA'))),
        primary key (id),
        unique (email)
    );

    create table user_admin_permissions (
        user_id bigint not null,
        permission varchar(255) check ((permission in ('SUPER','REGISTRAR','FINANCE','MOBILITY','SUPPORT','CONTENT')))
    );

    create table users (
        enabled boolean not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role varchar(255) not null check ((role in ('ADMIN','PROFESSOR','STUDENT'))),
        primary key (id)
    );

    alter table if exists add_drop_periods 
       add constraint FKpe4m0powhqhg1t85c3o466btg 
       foreign key (semester_id) 
       references semesters;

    alter table if exists assessment_components 
       add constraint FKa3s65sgn69fs88mxgncufkm7l 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists attendance_sessions 
       add constraint FKn8is0es149fgsbhoobjt7b9n0 
       foreign key (created_by_teacher_id) 
       references teachers;

    alter table if exists attendance_sessions 
       add constraint FK3ll2gu4k8fkrcngbpi4dvokmd 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists attendances 
       add constraint FKaebi93mdgaks11iy2xec1iqaa 
       foreign key (attendance_session_id) 
       references attendance_sessions;

    alter table if exists attendances 
       add constraint FK7bm4q4wptspkenhrsjgatdmk0 
       foreign key (student_id) 
       references students;

    alter table if exists attendances 
       add constraint FKhve0wfwhgf77vwjo7ebhb11dr 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists charges 
       add constraint FKrg7t93fj3x3npshkj28dh02aw 
       foreign key (student_id) 
       references students;

    alter table if exists checklist_items 
       add constraint FKacw9kfugpb1wax9i0vi84o8cg 
       foreign key (student_id) 
       references students;

    alter table if exists clearance_checkpoints 
       add constraint FKptlh2tnytnh8na4tykucs7yo9 
       foreign key (clearance_sheet_id) 
       references clearance_sheets;

    alter table if exists clearance_sheets 
       add constraint FKwyfae2jnydu320eau0kuh3ws 
       foreign key (student_id) 
       references students;

    alter table if exists course_announcements 
       add constraint FKh0e3fd6b6myiigwy0v5raemsl 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists course_announcements 
       add constraint FKlfw7ackpsji4gwbdw7fy8nukg 
       foreign key (teacher_id) 
       references teachers;

    alter table if exists course_materials 
       add constraint FKmmnpldmvojxr7w76jahuobu77 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists course_materials 
       add constraint FKfn4xiqeuf98kdybsp7xthw8f0 
       foreign key (uploaded_by_teacher_id) 
       references teachers;

    alter table if exists exam_schedules 
       add constraint FKu2hhjonsv5w11uv7yldt2rq5 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists file_assets 
       add constraint FKlj1owyg3rgdwv3fyjvx92hfm 
       foreign key (owner_student_id) 
       references students;

    alter table if exists file_assets 
       add constraint FKd3qgobfpnikyudmo0x52tpiu8 
       foreign key (uploaded_by_user_id) 
       references users;

    alter table if exists final_grades 
       add constraint FKn2qu6nork5xu36t98j3oe0ur0 
       foreign key (student_id) 
       references students;

    alter table if exists final_grades 
       add constraint FKmgbi4sa030oorg66ymt8jlgqb 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists fx_registrations 
       add constraint FKi49dpj4bpwn7hl72aobqio38p 
       foreign key (student_id) 
       references students;

    alter table if exists fx_registrations 
       add constraint FKdmj4xpp8714abe8ss9ehmlnoo 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists grade_change_requests 
       add constraint FKp1v8q7o5yeiy3wd38sx5a8ui6 
       foreign key (final_grade_id) 
       references final_grades;

    alter table if exists grade_change_requests 
       add constraint FKl76keyynx8wpgmcgme3d9dkih 
       foreign key (grade_id) 
       references grades;

    alter table if exists grade_change_requests 
       add constraint FKee6duar7u3bsqicogu4iomb7w 
       foreign key (reviewed_by_user_id) 
       references users;

    alter table if exists grade_change_requests 
       add constraint FKimyoosu28869ccfj407efans1 
       foreign key (student_id) 
       references students;

    alter table if exists grade_change_requests 
       add constraint FKspg7nfo7a2341ospg25m8rtdb 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists grade_change_requests 
       add constraint FKrpp6dftgtsawf097julscpyp5 
       foreign key (teacher_id) 
       references teachers;

    alter table if exists grades 
       add constraint FKo7fifsdtsdvw5vlyl6infsqx2 
       foreign key (assessment_component_id) 
       references assessment_components;

    alter table if exists grades 
       add constraint FK13a16545m7vvrcspc999r15s9 
       foreign key (student_id) 
       references students;

    alter table if exists grades 
       add constraint FK22pldk8wx5rehae65gvcd11es 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists holds 
       add constraint FK5cg5ectavllctvsiukw1k72tf 
       foreign key (student_id) 
       references students;

    alter table if exists meeting_times 
       add constraint FK38fgfanrp5nt80slgqqelm95t 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists mobility_applications 
       add constraint FKdqdoghqf7m3jg99bcesv7iubp 
       foreign key (student_id) 
       references students;

    alter table if exists payments 
       add constraint FKbstg5f3u4ikdd42t3fqr843j7 
       foreign key (charge_id) 
       references charges;

    alter table if exists payments 
       add constraint FK6ooq278k2bs5xi8t5o6oort1v 
       foreign key (student_id) 
       references students;

    alter table if exists programs 
       add constraint FKd6ajyvy0qh9iku1hoonr4ji4s 
       foreign key (faculty_id) 
       references faculties;

    alter table if exists registration_windows 
       add constraint FK9d2bsphsc5a58aesoeok5klar 
       foreign key (semester_id) 
       references semesters;

    alter table if exists registrations 
       add constraint FKcmo9lk1tap4hpbawuxhb8qf94 
       foreign key (student_id) 
       references students;

    alter table if exists registrations 
       add constraint FKorco0nydi6cchxbo1tyoqle5p 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists request_messages 
       add constraint FK4di5pogfg8ox60tjudcnkqkkl 
       foreign key (request_id) 
       references student_requests;

    alter table if exists request_messages 
       add constraint FKldud6vqb7o1f9k29s5et16hv3 
       foreign key (sender_user_id) 
       references users;

    alter table if exists social_activities 
       add constraint FKbprii7fuq0ql4vk8191v4v088 
       foreign key (student_id) 
       references students;

    alter table if exists student_files 
       add constraint FKfxrp5jln9qbx28u4qq9kedhjq 
       foreign key (student_id) 
       references students;

    alter table if exists student_requests 
       add constraint FKaksfulqe7wtcl5eqi22hwupmn 
       foreign key (assigned_to_user_id) 
       references users;

    alter table if exists student_requests 
       add constraint FKkqg5uy7rwanppd1dm01hdfci 
       foreign key (student_id) 
       references students;

    alter table if exists students 
       add constraint FKrmv2t2u8eqkw9krx0tmogghio 
       foreign key (current_semester_id) 
       references semesters;

    alter table if exists students 
       add constraint FKjy3uttpwfpb0s83e2pvpatg9j 
       foreign key (faculty_id) 
       references faculties;

    alter table if exists students 
       add constraint FKosyri4p0rpereimcss9cm3cwv 
       foreign key (program_id) 
       references programs;

    alter table if exists subject_offerings 
       add constraint FKqfydfhflskcjg8abw2l61807b 
       foreign key (semester_id) 
       references semesters;

    alter table if exists subject_offerings 
       add constraint FKmqxdwbcmu9b3vwqdob6ygdmlm 
       foreign key (subject_id) 
       references subjects;

    alter table if exists subject_offerings 
       add constraint FK8bd3n6fwrqien4h6qpl8udj83 
       foreign key (teacher_id) 
       references teachers;

    alter table if exists subject_prerequisites 
       add constraint FK8vcc3x4jk5nyevql4tbg04rlx 
       foreign key (prerequisite_id) 
       references subjects;

    alter table if exists subject_prerequisites 
       add constraint FKi2pk0tltinduehdgkvotwwa2b 
       foreign key (subject_id) 
       references subjects;

    alter table if exists subjects 
       add constraint FKqwmhvc2y5xko5p2d7wn70ea7f 
       foreign key (program_id) 
       references programs;

    alter table if exists survey_questions 
       add constraint FK91fvqiwu0dj35uxpnx7qpoiw6 
       foreign key (survey_id) 
       references surveys;

    alter table if exists survey_responses 
       add constraint FKdprntjt0uh0ciysb95dcaxrpj 
       foreign key (student_id) 
       references students;

    alter table if exists survey_responses 
       add constraint FKg5uul15qxrqgdet2fa3wvdhj8 
       foreign key (survey_id) 
       references surveys;

    alter table if exists surveys 
       add constraint FKrhhk021s13qk1jdqe3jatc4vx 
       foreign key (semester_id) 
       references semesters;

    alter table if exists teacher_student_notes 
       add constraint FKli7q9tsmrgdn87p5dbbmy71xf 
       foreign key (student_id) 
       references students;

    alter table if exists teacher_student_notes 
       add constraint FK8dhp7ieuy9byd0blvtxb7lma1 
       foreign key (subject_offering_id) 
       references subject_offerings;

    alter table if exists teacher_student_notes 
       add constraint FKgvucevtn8lpu61x59uy1hn8jm 
       foreign key (teacher_id) 
       references teachers;

    alter table if exists teachers 
       add constraint FKt9rth51e1sfx7dox4m60qnjh6 
       foreign key (faculty_id) 
       references faculties;

    alter table if exists user_admin_permissions 
       add constraint FKiv6mbrubu9trbaww3104c6wda 
       foreign key (user_id) 
       references users;
