create table chat_rooms (
    id bigint generated by default as identity primary key,
    name varchar(255),
    type varchar(20) not null check (type in ('SECTION','DIRECT')),
    section_id bigint,
    created_at timestamp(6) with time zone not null,
    constraint fk_chat_rooms_section foreign key (section_id) references subject_offerings(id)
);

create table chat_room_members (
    id bigint generated by default as identity primary key,
    chat_room_id bigint not null,
    user_id bigint not null,
    joined_at timestamp(6) with time zone not null,
    constraint fk_chat_members_room foreign key (chat_room_id) references chat_rooms(id),
    constraint fk_chat_members_user foreign key (user_id) references users(id),
    unique (chat_room_id, user_id)
);

create table chat_messages (
    id bigint generated by default as identity primary key,
    chat_room_id bigint not null,
    sender_user_id bigint not null,
    content text not null,
    created_at timestamp(6) with time zone not null,
    constraint fk_chat_msg_room foreign key (chat_room_id) references chat_rooms(id),
    constraint fk_chat_msg_sender foreign key (sender_user_id) references users(id)
);

create index idx_chat_messages_room_created on chat_messages(chat_room_id, created_at desc);
create index idx_chat_room_members_user on chat_room_members(user_id);
create index idx_chat_rooms_section on chat_rooms(section_id);
