-- =============================================
-- V8: Dorm Registration, Food Ordering, Campus Map, Laundry Booking
-- =============================================

-- ==================== DORM ====================

create table dorm_buildings (
    id bigint generated by default as identity,
    name varchar(255) not null,
    address varchar(255),
    total_floors integer not null default 1,
    primary key (id)
);

create table dorm_rooms (
    id bigint generated by default as identity,
    dorm_building_id bigint not null references dorm_buildings(id),
    room_number varchar(50) not null,
    floor integer not null,
    room_type varchar(50) not null check (room_type in ('SINGLE_SUITE','DOUBLE_ROOM')),
    price_per_semester numeric(12,2) not null,
    capacity integer not null,
    occupied integer not null default 0,
    description varchar(500),
    primary key (id),
    unique (dorm_building_id, room_number)
);

create table dorm_applications (
    id bigint generated by default as identity,
    student_id bigint not null references students(id),
    dorm_room_id bigint references dorm_rooms(id),
    status varchar(50) not null check (status in ('DRAFT','SUBMITTED','APPROVED','REJECTED','CANCELLED')),
    current_step integer not null default 1,
    room_type_preference varchar(50) check (room_type_preference in ('SINGLE_SUITE','DOUBLE_ROOM')),
    sleep_schedule varchar(100),
    study_environment varchar(100),
    preferred_roommate_uid varchar(255),
    terms_accepted boolean not null default false,
    emergency_contact_name varchar(255),
    emergency_contact_phone varchar(100),
    special_needs text,
    created_at timestamp(6) with time zone not null default now(),
    updated_at timestamp(6) with time zone not null default now(),
    primary key (id)
);

-- ==================== FOOD ====================

create table food_categories (
    id bigint generated by default as identity,
    name varchar(100) not null,
    icon varchar(50),
    sort_order integer not null default 0,
    primary key (id)
);

create table food_items (
    id bigint generated by default as identity,
    category_id bigint not null references food_categories(id),
    name varchar(255) not null,
    description varchar(500),
    price numeric(10,2) not null,
    image_url varchar(500),
    available boolean not null default true,
    popular boolean not null default false,
    primary key (id)
);

create table food_orders (
    id bigint generated by default as identity,
    student_id bigint not null references students(id),
    status varchar(50) not null check (status in ('PENDING','CONFIRMED','READY','PICKED_UP','CANCELLED')),
    total_amount numeric(10,2) not null,
    created_at timestamp(6) with time zone not null default now(),
    updated_at timestamp(6) with time zone not null default now(),
    pickup_time timestamp(6) with time zone,
    note varchar(500),
    primary key (id)
);

create table food_order_items (
    id bigint generated by default as identity,
    order_id bigint not null references food_orders(id) on delete cascade,
    food_item_id bigint not null references food_items(id),
    quantity integer not null default 1,
    unit_price numeric(10,2) not null,
    primary key (id)
);

-- ==================== CAMPUS MAP ====================

create table campus_buildings (
    id bigint generated by default as identity,
    name varchar(255) not null,
    code varchar(50),
    description varchar(500),
    building_type varchar(100) check (building_type in ('ACADEMIC','LIBRARY','LECTURE_HALL','LAB','ADMIN','DORM','CANTEEN','SPORT','OTHER')),
    latitude double precision,
    longitude double precision,
    floor_count integer not null default 1,
    image_url varchar(500),
    primary key (id)
);

create table campus_rooms (
    id bigint generated by default as identity,
    building_id bigint not null references campus_buildings(id),
    room_number varchar(50) not null,
    floor integer not null,
    room_type varchar(100) check (room_type in ('CLASSROOM','LECTURE_HALL','LAB','OFFICE','LIBRARY','COMPUTER_CENTER','CANTEEN','OTHER')),
    name varchar(255),
    description varchar(500),
    capacity integer,
    latitude double precision,
    longitude double precision,
    primary key (id),
    unique (building_id, room_number)
);

create table campus_navigation_edges (
    id bigint generated by default as identity,
    from_room_id bigint references campus_rooms(id),
    to_room_id bigint references campus_rooms(id),
    from_building_id bigint references campus_buildings(id),
    to_building_id bigint references campus_buildings(id),
    distance_meters double precision not null,
    is_accessible boolean not null default true,
    primary key (id)
);

-- ==================== LAUNDRY ====================

create table laundry_rooms (
    id bigint generated by default as identity,
    name varchar(255) not null,
    dorm_building_id bigint references dorm_buildings(id),
    total_machines integer not null default 12,
    primary key (id)
);

create table laundry_machines (
    id bigint generated by default as identity,
    laundry_room_id bigint not null references laundry_rooms(id),
    machine_number integer not null,
    status varchar(50) not null check (status in ('AVAILABLE','IN_USE','OUT_OF_ORDER')) default 'AVAILABLE',
    primary key (id),
    unique (laundry_room_id, machine_number)
);

create table laundry_bookings (
    id bigint generated by default as identity,
    student_id bigint not null references students(id),
    machine_id bigint not null references laundry_machines(id),
    time_slot_start timestamp(6) with time zone not null,
    time_slot_end timestamp(6) with time zone not null,
    status varchar(50) not null check (status in ('BOOKED','IN_PROGRESS','COMPLETED','CANCELLED')) default 'BOOKED',
    created_at timestamp(6) with time zone not null default now(),
    primary key (id)
);
